import maplibregl from "maplibre-gl";

// The fill/line paint is a pure function of the static config + warn-level
// tables, so it is built once. It reads three feature-states per region —
// `state` (cf. getRegionState), `warnlevel`, `intern` — set by the effect
// below; selection / hover / filter changes only update those feature-states,
// never the paint expression.

export const REGION_FILL_PAINT = Object.freeze({
  "fill-color": [
    "match",
    ["coalesce", ["feature-state", "state"], "default"],
    // n/a / no-rating regions carry no warnlevel, so their colour depends on
    // the state alone — the per-warnlevel arms are unreachable and collapse away.
    "noData",
    "#19abff",
    "noDataMouseOver",
    "#19abff",
    "noDataGrey",
    "#888888",
    "noDataGreyMouseOver",
    "#888888",
    "noDataPartialMouseOver",
    "#888888",
    [
      "case",
      // no-rating regions (warnlevel 0)
      ["==", ["coalesce", ["feature-state", "warnlevel"], 0], 0],
      "#ffffff",
      // rated regions: keyed by the full state/warnlevel/intern triple.
      [
        "match",
        [
          "concat",
          ["coalesce", ["feature-state", "state"], "default"],
          "/",
          ["to-string", ["coalesce", ["feature-state", "warnlevel"], 0]],
          "/",
          ["to-string", ["coalesce", ["feature-state", "intern"], false]]
        ],
        "mouseOver/1/true",
        "#ccff66",
        "mouseOver/2/true",
        "#ffff00",
        "mouseOver/3/true",
        "#ff9900",
        "mouseOver/4/true",
        "#ff0000",
        "mouseOver/5/true",
        "#000000",
        "mouseOver/1/false",
        "#ccff66",
        "mouseOver/2/false",
        "#ffff00",
        "mouseOver/3/false",
        "#ff9900",
        "mouseOver/4/false",
        "#ff0000",
        "mouseOver/5/false",
        "#000000",
        "selected/1/true",
        "#ccff66",
        "selected/2/true",
        "#ffff00",
        "selected/3/true",
        "#ff9900",
        "selected/4/true",
        "#ff0000",
        "selected/5/true",
        "#000000",
        "selected/1/false",
        "#ccff66",
        "selected/2/false",
        "#ffff00",
        "selected/3/false",
        "#ff9900",
        "selected/4/false",
        "#ff0000",
        "selected/5/false",
        "#000000",
        "highlighted/1/true",
        "#ccff66",
        "highlighted/2/true",
        "#ffff00",
        "highlighted/3/true",
        "#ff9900",
        "highlighted/4/true",
        "#ff0000",
        "highlighted/5/true",
        "#000000",
        "highlighted/1/false",
        "#ccff66",
        "highlighted/2/false",
        "#ffff00",
        "highlighted/3/false",
        "#ff9900",
        "highlighted/4/false",
        "#ff0000",
        "highlighted/5/false",
        "#000000",
        "dehighlighted/1/true",
        "#f2ffd9",
        "dehighlighted/2/true",
        "#ffffbf",
        "dehighlighted/3/true",
        "#ffe6bf",
        "dehighlighted/4/true",
        "#ffbfbf",
        "dehighlighted/5/true",
        "#c9c9c9",
        "dehighlighted/1/false",
        "#f8ffe9",
        "dehighlighted/2/false",
        "#ffffdb",
        "dehighlighted/3/false",
        "#fff0db",
        "dehighlighted/4/false",
        "#ffdbdb",
        "dehighlighted/5/false",
        "#dbdbdb",
        "dimmed/1/true",
        "#e6ffb3",
        "dimmed/2/true",
        "#ffff80",
        "dimmed/3/true",
        "#ffcc80",
        "dimmed/4/true",
        "#ff8080",
        "dimmed/5/true",
        "#8e8e8e",
        "dimmed/1/false",
        "#eeffcc",
        "dimmed/2/false",
        "#ffffaa",
        "dimmed/3/false",
        "#ffddaa",
        "dimmed/4/false",
        "#ffaaaa",
        "dimmed/5/false",
        "#aaaaaa",
        "default/1/true",
        "#ccff66",
        "default/2/true",
        "#ffff00",
        "default/3/true",
        "#ff9900",
        "default/4/true",
        "#ff0000",
        "default/5/true",
        "#000000",
        "default/1/false",
        "#ccff66",
        "default/2/false",
        "#ffff00",
        "default/3/false",
        "#ff9900",
        "default/4/false",
        "#ff0000",
        "default/5/false",
        "#000000",
        "#ffffff"
      ]
    ]
  ],
  "fill-opacity": [
    "match",
    ["coalesce", ["feature-state", "state"], "default"],
    // n/a / no-rating regions carry no warnlevel, so their opacity depends on
    // the state alone — the per-warnlevel arms (incl. the slightly different
    // `/5/`) are unreachable and collapse away.
    "noData",
    0.5,
    "noDataMouseOver",
    0.75,
    "noDataGrey",
    0.5,
    "noDataGreyMouseOver",
    0.75,
    "noDataPartialMouseOver",
    0.75,
    [
      "case",
      // no-rating regions (warnlevel 0)
      ["==", ["coalesce", ["feature-state", "warnlevel"], 0], 0],
      0,
      // rated regions: opacity depends only on state + intern (warnlevel is
      // irrelevant once the slight /5/ differences are ignored).
      [
        "match",
        [
          "concat",
          ["coalesce", ["feature-state", "state"], "default"],
          "/",
          ["to-string", ["coalesce", ["feature-state", "intern"], false]]
        ],
        "mouseOver/true",
        1,
        "mouseOver/false",
        0.5,
        "selected/true",
        1,
        "selected/false",
        0.5,
        "highlighted/true",
        1,
        "highlighted/false",
        0.5,
        "dehighlighted/true",
        1,
        "dehighlighted/false",
        0.875,
        "dimmed/true",
        1,
        "dimmed/false",
        0.75,
        "default/true",
        1,
        "default/false",
        0.5,
        0
      ]
    ]
  ]
} satisfies maplibregl.FillLayerSpecification["paint"]);

export const REGION_LINE_PAINT = Object.freeze({
  "line-color": [
    "match",
    ["coalesce", ["feature-state", "state"], "default"],
    "mouseOver",
    "#555555",
    "selected",
    "#555555",
    "noDataPartialMouseOver",
    "#555555",
    "default",
    "#aaaaaa",
    "#aaaaaa"
  ],
  "line-width": [
    "match",
    ["coalesce", ["feature-state", "state"], "default"],
    "mouseOver",
    2,
    "selected",
    2,
    "noDataPartialMouseOver",
    2,
    "default",
    1,
    1
  ],
  "line-opacity": [
    "match",
    ["coalesce", ["feature-state", "state"], "default"],
    "mouseOver",
    1,
    "selected",
    1,
    "noDataPartialMouseOver",
    1,
    "default",
    0,
    0
  ]
} satisfies maplibregl.LineLayerSpecification["paint"]);
