// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vError = v.object({
  error: v.string()
});

/**
 * Optional metadata projected into CAAML-aligned columns. All fields are optional; the server derives sensible defaults where possible.
 *
 */
export const vProfileMeta = v.object({
  record_time: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  date_time_report: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  date_time_last_edit: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  src_type: v.optional(v.string()),
  src_name: v.optional(v.string()),
  src_email: v.optional(v.pipe(v.string(), v.email())),
  loc_name: v.optional(v.string()),
  elevation_m: v.optional(v.number()),
  aspect: v.optional(v.string()),
  slope_angle_deg: v.optional(v.number()),
  latitude: v.optional(v.number()),
  longitude: v.optional(v.number()),
  country: v.optional(v.string()),
  region: v.optional(v.string()),
  region_id: v.optional(v.string()),
  hs_cm: v.optional(v.number()),
  ect_score: v.optional(v.string()),
  rb_score: v.optional(v.string()),
  application: v.optional(v.string()),
  application_version: v.optional(v.string())
});

/**
 * Upload envelope carrying the CAAML XML plus projected metadata.
 */
export const vProfileUpload = v.object({
  caaml: v.string(),
  edit_token: v.optional(v.string()),
  meta: v.optional(vProfileMeta)
});

/**
 * Overall snow-profile stability class, derived from the stored ECT/RB test scores (see backend `deriveStability`). `no-test` means the profile carries no classifiable ECT/RB test. Clients map the class to a display colour (profea's STABILITY_PALETTE). Ordered best → worst.
 *
 */
export const vStability = v.picklist([
  "good",
  "fair",
  "poor",
  "very-poor",
  "no-test"
]);

/**
 * Lightweight projection of a stored profile (no CAAML XML), returned by `GET /profiles/export?format=json` for map/list views. Every field is always present; all but `id` and `stability` may be `null` when the stored profile carries no value for them.
 *
 */
export const vProfileListItem = v.object({
  id: v.string(),
  dateTime: v.nullish(v.pipe(v.string(), v.isoTimestamp())),
  latitude: v.nullish(v.number()),
  longitude: v.nullish(v.number()),
  region: v.nullish(v.string()),
  regionId: v.nullish(v.string()),
  location: v.nullish(v.string()),
  elevation: v.nullish(v.number()),
  aspect: v.nullish(v.string()),
  snowHeight: v.nullish(v.number()),
  stability: v.optional(vStability)
});

export const vCreateProfileResponse = v.object({
  profile_id: v.string(),
  edit_token: v.string()
});

export const vUpdateProfileResponse = v.object({
  profile_id: v.string()
});

/**
 * Assigned profile id, e.g. `AT-07-14-20260605-01`.
 */
export const vProfileId = v.string();

export const vCreateProfileBody = vProfileUpload;

/**
 * Profile created.
 */
export const vCreateProfileResponse2 = vCreateProfileResponse;

export const vExportProfilesQuery = v.object({
  format: v.optional(v.picklist(["xml", "zip", "json"]), "xml"),
  regions: v.optional(v.string()),
  dateFrom: v.optional(v.pipe(v.string(), v.isoDate())),
  dateTo: v.optional(v.pipe(v.string(), v.isoDate()))
});

/**
 * Matching profiles.
 */
export const vExportProfilesResponse = v.array(vProfileListItem);

export const vGetProfilePath = v.object({
  id: v.string()
});

export const vGetProfileQuery = v.object({
  format: v.optional(v.picklist(["xml"]), "xml")
});

/**
 * The profile as CAAML XML.
 */
export const vGetProfileResponse = v.string();

export const vUpdateProfileBody = vProfileUpload;

export const vUpdateProfilePath = v.object({
  id: v.string()
});

export const vUpdateProfileQuery = v.object({
  token: v.optional(v.string())
});

/**
 * Profile updated.
 */
export const vUpdateProfileResponse2 = vUpdateProfileResponse;

export const vVerifyEditTokenBody = v.object({
  edit_token: v.string()
});

export const vVerifyEditTokenPath = v.object({
  id: v.string()
});

/**
 * Token matches.
 */
export const vVerifyEditTokenResponse = v.void();

export const vGetProfileSvgPath = v.object({
  id: v.string()
});

export const vGetProfileSvgQuery = v.object({
  lang: v.optional(v.picklist(["en", "de"]), "en"),
  colorizeByGrain: v.optional(v.boolean(), true),
  hardnessDisplay: v.optional(v.picklist(["both", "hand", "ram"]), "both")
});

/**
 * The rendered profile.
 */
export const vGetProfileSvgResponse = v.string();
